### PR TITLE
Microsoft.NET.Sdk.IL updated to the latest 3.0.0-preview-27318-01 version.

### PR DESCRIPTION
**Pull request by konard**
Code simplified even more.
Everything tested to work again.

### CODE REVIEW

**Comment by jvbsl** [comment]
Thanks again.
Should I merge this directly, or do you plan to still do stuff on it?

**Comment by konard** [comment]
This is the last change for today. So you can merge it.

**Comment by konard** [comment]
Thank you too. Your initial commit saved me a lot of time. I wasted about an hour or two trying to compile corefx with no luck.

**Comment by jvbsl** [comment]
Yeah no problem. I only uploaded it to have a sample project for an issue for rider: https://youtrack.jetbrains.com/issue/RIDER-32352

**Comment by konard** [comment]
That is nice that Rider can handle it. Visual Studio 2019 just fails to load the project at the moment.

**Pull request merged**
